notifications:
  email: false
language: node_js
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
jobs:
  include:
  - stage: build
    script:
    - npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: "$GH_PAGES_DEPLOY_TOKEN"
  keep-history: true
  on:
    branch: master